# Generated by Django 4.2.2 on 2024-08-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Habit place", max_length=50, verbose_name="Place"
                    ),
                ),
                ("time", models.TimeField(help_text="Habit time", verbose_name="Time")),
                (
                    "action",
                    models.CharField(
                        help_text="Habit action", max_length=50, verbose_name="Action"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Is habit pleasant?",
                        verbose_name="Pleasant",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Edit habit periodicity in days",
                        verbose_name="Periodicity",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        help_text="Edit award for doing habit",
                        max_length=50,
                        verbose_name="Award",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Edit habit execution time in seconds",
                        verbose_name="Execution time",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Is habit for public view?",
                        verbose_name="Public",
                    ),
                ),
                (
                    "related_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habits",
                        verbose_name="Related habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
    ]
