# Generated by Django 4.2.2 on 2024-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="award",
            field=models.CharField(
                blank=True,
                help_text="Edit award for doing habit",
                max_length=50,
                null=True,
                verbose_name="Award",
            ),
        ),
    ]
